name: ourchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  provider: ^6.1.5
  get_it: ^8.0.3
  file_picker: ^10.2.0
  flutter_spinkit: ^5.2.1
  timeago: ^3.7.1
  record: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.5.0
  http: ^1.2.1


  permission_handler: ^11.3.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
